version: "3.4"
services:
  relay:
    build:
      context: ./build-connect
      args:
        RELEASE_TAG: 52d62410d16eb394e2253360a6c679c02a7742a6
    restart: unless-stopped
    environment:
      - ADMIN_CLIENT_HOST=
      - APP_SERVICE_PORT=8080
      - MQTT_HTTP_PORT=1883
      - MQTT_SKIP_USER_CHECK=1
      - APP_WORKER_COUNT=2
    ports:
      - "8080"
    image: "relay.lattice-connect.public.dappnode.eth:1.0.0"
volumes:
  lattice-connect: {}
