version: "3.4"
services:
  relay:
    build: ./build-connect
    restart: unless-stopped
    environment:
      - BROKER_USERNAME=connector
      - BROKER_PASSWORD=changeMePlease
      - MQTT_BROKER_LADDR=
      - APP_RPC_LADDR=
      - LOG_LEVEL=trace
    ports:
      - "3000:3000"
      - "1883:1883"
    image: "relay.lattice-connect.public.dappnode.eth:0.1.0"
  wallet:
    build: ./build-ui
    restart: unless-stopped
    image: "wallet.lattice-connect.public.dappnode.eth:0.1.0"
